version: "3.8"

services:
  db:
    image: karthik621/home:dbimage
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    deploy:
      replicas: 1

  auth_service:
    image: karthik621/home:authimage
    ports:
      - "5001:5001"
    networks:
      - mynetwork
    deploy:
      replicas: 1

  book_service:
    image: karthik621/home:bookimage
    ports:
      - "5002:5002"
    networks:
      - mynetwork
    deploy:
      replicas: 1

  borrow_service:
    image: karthik621/home:borrowimage
    ports:
      - "5003:5003"
    networks:
      - mynetwork
    deploy:
      replicas: 1

  app_service:
    image: karthik621/home:appimage
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    deploy:
      replicas: 1

networks:
  mynetwork:
    driver: overlay
